/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import logica.LogicaNegocio;
import pa.cifpaviles.dam.aeropuertoclase.dto.Aeropuerto;

/**
 *
 * @author mariorl
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
    }
    
    private void cargaaeropuertos(){
        Aeropuerto a1 = new Aeropuerto("AMS","Aeropuerto de Amsterdam-Schiphol","Amsterdam");
        LogicaNegocio.addAeropuerto(a1);
        /*AMS;Aeropuerto de Amsterdam-Schiphol;Amsterdam
ABC;Aeropuerto de Albacete;Albacete
BCN;Aeropuerto de Barcelona-El Prat;Barcelona
BIO;Aeropuerto de Bilbao;Bilbao*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        btnAddCompany = new javax.swing.JButton();
        btnAddVuelo = new javax.swing.JButton();
        btnModCompany = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        mnuPricipal = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuAddCompany = new javax.swing.JMenuItem();
        mnuAddVuelo = new javax.swing.JMenuItem();
        mnuDatos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("BIENVENIDO");

        btnAddCompany.setActionCommand("Añadir Compañia Aerea");
        btnAddCompany.setLabel("Añadir Compañia Aerea");
        btnAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompanyActionPerformed(evt);
            }
        });

        btnAddVuelo.setLabel("Añadir Vuelo");
        btnAddVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVueloActionPerformed(evt);
            }
        });

        btnModCompany.setText("Ver y modificar compañias");
        btnModCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCompanyActionPerformed(evt);
            }
        });

        jButton4.setText("Ver Modificar Vuelos");

        mnuOpciones.setLabel("Opciones");
        mnuOpciones.setName(""); // NOI18N

        mnuAddCompany.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuAddCompany.setActionCommand("Añadir Compañia");
        mnuAddCompany.setLabel("Añadir Aeropuerto");
        mnuAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddCompanyActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuAddCompany);

        mnuAddVuelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuAddVuelo.setLabel("Añadir Vuelo");
        mnuAddVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddVueloActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuAddVuelo);

        mnuPricipal.add(mnuOpciones);

        mnuDatos.setLabel("Ver Datos");
        mnuPricipal.add(mnuDatos);

        setJMenuBar(mnuPricipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddCompany)
                            .addComponent(btnModCompany))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddVuelo)
                            .addComponent(jButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCompany)
                    .addComponent(btnAddVuelo))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModCompany)
                    .addComponent(jButton4))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompanyActionPerformed
        PaginaCompany pag=new PaginaCompany();
        pag.setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_btnAddCompanyActionPerformed

    private void btnAddVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVueloActionPerformed
        PaginaVuelosBase pag=new PaginaVuelosBase();
        pag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddVueloActionPerformed

    private void mnuAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddCompanyActionPerformed
        PaginaCompany pag=new PaginaCompany();
        pag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuAddCompanyActionPerformed

    private void mnuAddVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddVueloActionPerformed
        PaginaVuelosBase pag=new PaginaVuelosBase();
        pag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuAddVueloActionPerformed

    private void btnModCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCompanyActionPerformed
        PaginaModCompany pag=new PaginaModCompany();
        pag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCompany;
    private javax.swing.JButton btnAddVuelo;
    private javax.swing.JButton btnModCompany;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JMenuItem mnuAddCompany;
    private javax.swing.JMenuItem mnuAddVuelo;
    private javax.swing.JMenu mnuDatos;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuBar mnuPricipal;
    // End of variables declaration//GEN-END:variables
}
