/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.MenuInicio;
import java.util.List;
import logica.LogicaNegocio;
import pa.cifpaviles.dam.aeropuertoclase.dto.Aeropuerto;

/**
 *
 * @author mariorl
 */
public class PaginaVuelosBase extends javax.swing.JFrame {

    /**
     * Creates new form PaginaVuelos
     */
    public PaginaVuelosBase() {
        initComponents();

        lstOrigen = LogicaNegocio.rellenarListaAeropuertos(lstOrigen);
        lstDestino = LogicaNegocio.rellenarListaAeropuertos(lstDestino);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlazas = new javax.swing.JLabel();
        lblHoraS = new javax.swing.JLabel();
        txtHoraS = new javax.swing.JTextField();
        txtNumeroPlazas = new javax.swing.JTextField();
        lblCodigoV = new javax.swing.JLabel();
        lblAeropuertoO = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblAeropuertoD = new javax.swing.JLabel();
        lblHoraL = new javax.swing.JLabel();
        txtHoraL = new javax.swing.JTextField();
        lblDias = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lstOrigen = new javax.swing.JComboBox<>();
        lstDestino = new javax.swing.JComboBox<>();
        mnuPricipal = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuAddCompany = new javax.swing.JMenuItem();
        mnuAddVuelo = new javax.swing.JMenuItem();
        mnuDatos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPlazas.setText("Numero de Plazas:");

        lblHoraS.setText("Hora de Salida:");

        lblCodigoV.setText("Codigo de Vuelo:");

        lblAeropuertoO.setText("Aeropuerto de Origen:");

        lblAeropuertoD.setText("Aeropuerto de Destino:");

        lblHoraL.setText("Hora de Llegada:");

        lblDias.setText("DIas que Opera:");

        btnVolver.setLabel("Volver al Menu Pricipal");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAdd.setLabel("Añadir");

        lstOrigen.setMaximumRowCount(100);
        lstOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstOrigenActionPerformed(evt);
            }
        });

        mnuOpciones.setLabel("Opciones");
        mnuOpciones.setName(""); // NOI18N

        mnuAddCompany.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuAddCompany.setLabel("Añadir Compañia");
        mnuAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddCompanyActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuAddCompany);

        mnuAddVuelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuAddVuelo.setLabel("Añadir Vuelo");
        mnuAddVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddVueloActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuAddVuelo);

        mnuPricipal.add(mnuOpciones);

        mnuDatos.setLabel("Ver Datos");
        mnuPricipal.add(mnuDatos);

        setJMenuBar(mnuPricipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoraL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoV)
                            .addComponent(lblPlazas)
                            .addComponent(lblHoraS)
                            .addComponent(lblDias)
                            .addComponent(lblAeropuertoD)
                            .addComponent(lblAeropuertoO))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(btnAdd))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoraL)
                            .addComponent(txtNumeroPlazas)
                            .addComponent(txtHoraS)
                            .addComponent(txtDias)
                            .addComponent(lstOrigen, 0, 325, Short.MAX_VALUE)
                            .addComponent(lstDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoV)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAeropuertoO)
                    .addComponent(lstOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAeropuertoD)
                    .addComponent(lstDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlazas)
                    .addComponent(txtNumeroPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraS)
                    .addComponent(txtHoraS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraL)
                    .addComponent(txtHoraL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDias)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnAdd))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuInicio menu=new MenuInicio();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void mnuAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddCompanyActionPerformed
        PaginaCompany pag=new PaginaCompany();
        pag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuAddCompanyActionPerformed

    private void mnuAddVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddVueloActionPerformed
        PaginaVuelosBase pag=new PaginaVuelosBase();
        pag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuAddVueloActionPerformed

    private void lstOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaVuelosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaVuelosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaVuelosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaVuelosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaVuelosBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnVolver;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAeropuertoD;
    private javax.swing.JLabel lblAeropuertoO;
    private javax.swing.JLabel lblCodigoV;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblHoraL;
    private javax.swing.JLabel lblHoraS;
    private javax.swing.JLabel lblPlazas;
    private javax.swing.JComboBox<String> lstDestino;
    private javax.swing.JComboBox<String> lstOrigen;
    private javax.swing.JMenuItem mnuAddCompany;
    private javax.swing.JMenuItem mnuAddVuelo;
    private javax.swing.JMenu mnuDatos;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuBar mnuPricipal;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtHoraL;
    private javax.swing.JTextField txtHoraS;
    private javax.swing.JTextField txtNumeroPlazas;
    // End of variables declaration//GEN-END:variables
}
